FROM openjdk:8u151-jdk

RUN apt-get update && apt-get install -y netcat

COPY ./squirrel.worker/target/squirrel.worker.jar /data/squirrel/squirrel.jar
COPY ./spring-config/default-config.xml /data/squirrel/default-config.xml
WORKDIR /data/squirrel

#ADD entrypoint.sh /entrypoint.sh
#RUN chmod +x /entrypoint.sh

VOLUME ["/var/squirrel/data"]

CMD java -cp squirrel.jar:. org.aksw.simba.squirrel.components.WorkerComponentStarter
