<<>> <http://purl.org/dc/terms/creator> <http://www.blogger.com/profile/1109404> .
<http://www.blogger.com/profile/1109404> <http://xmlns.com/foaf/0.1/img> <<>> .
<<>> <http://purl.org/dc/terms/title> "Portrait of Mark" .