_:n0 <http://www.w3.org/1999/xhtml/vocab#definition> "a bi-pedal primate" .
_:n0 <http://www.w3.org/1999/xhtml/vocab#note> "confused animal" .
_:n0 <http://www.w3.org/1999/xhtml/vocab#foo> "Milky Way" .
