_:n0 <http://xmlns.com/foaf/0.1/mbox> <mailto:manu.sporny@digitalbazaar.com> .
_:n0 <http://xmlns.com/foaf/0.1/knows> _:n1 .
_:n1 <http://xmlns.com/foaf/0.1/knows> _:n0 .
_:n1 <http://xmlns.com/foaf/0.1/mbox> <mailto:gregg@kellogg-assoc.com> .