_:n1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
<http://www.example.org/#ben> <http://xmlns.com/foaf/0.1/knows> _:n1 .
_:n1 <http://xmlns.com/foaf/0.1/name> "Mark Birbeck" .
_:n2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
<http://www.example.org/#ben> <http://xmlns.com/foaf/0.1/knows> _:n2 .
_:n2 <http://xmlns.com/foaf/0.1/name> "Ivan Herman" .