<<>> <http://www.w3.org/1999/xhtml/vocab#alternate> "alternate" .
<<>> <http://www.w3.org/1999/xhtml/vocab#appendix> "appendix" .
<<>> <http://www.w3.org/1999/xhtml/vocab#cite> "cite" .
<<>> <http://www.w3.org/1999/xhtml/vocab#bookmark> "bookmark" .
<<>> <http://www.w3.org/1999/xhtml/vocab#contents> "contents" .
<<>> <http://www.w3.org/1999/xhtml/vocab#chapter> "chapter" .
<<>> <http://www.w3.org/1999/xhtml/vocab#copyright> "copyright" .
<<>> <http://www.w3.org/1999/xhtml/vocab#first> "first" .
<<>> <http://www.w3.org/1999/xhtml/vocab#glossary> "glossary" .
<<>> <http://www.w3.org/1999/xhtml/vocab#help> "help" .
<<>> <http://www.w3.org/1999/xhtml/vocab#icon> "icon" .
<<>> <http://www.w3.org/1999/xhtml/vocab#index> "index" .
<<>> <http://www.w3.org/1999/xhtml/vocab#last> "last" .
<<>> <http://www.w3.org/1999/xhtml/vocab#license> "license" .
<<>> <http://www.w3.org/1999/xhtml/vocab#meta> "meta" .
<<>> <http://www.w3.org/1999/xhtml/vocab#next> "next" .
<<>> <http://www.w3.org/1999/xhtml/vocab#prev> "prev" .
<<>> <http://www.w3.org/1999/xhtml/vocab#previous> "previous" .
<<>> <http://www.w3.org/1999/xhtml/vocab#section> "section" .
<<>> <http://www.w3.org/1999/xhtml/vocab#start> "start" .
<<>> <http://www.w3.org/1999/xhtml/vocab#stylesheet> "stylesheet" .
<<>> <http://www.w3.org/1999/xhtml/vocab#subsection> "subsection" .
<<>> <http://www.w3.org/1999/xhtml/vocab#top> "top" .
<<>> <http://www.w3.org/1999/xhtml/vocab#up> "up" .
<<>> <http://www.w3.org/1999/xhtml/vocab#p3pv1> "p3pv1" .