<http://example.org/profiles/director.html> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/Role> .
_:n0 <http://www.w3.org/2000/01/rdf-schema#label> <http://example.org/profiles/director.html> .
<<>> <http://example.org/role> _:n0 .