<<>> <http://www.w3.org/ns/rdfa#usesVocabulary> <http://schema.org/> .
_:n0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
_:n0 <http://schema.org/name> "Gregg" .
_:n0 <http://schema.org/name> "Kellogg" .