package org.aksw.simba.squirrel.utils.vocabularies;

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;


/**
 * Vocabulary definitions from /home/ivierle/cube/schema.ttl 
 * @author Auto-generated by schemagen on 23 Feb 2018 18:07 
 */
public class CreativeCommons
{
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://creativecommons.org/ns#";

    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI()
    {
        return NS;
    }

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);

    //sadly JENA schemagen is only able to generate the header from file, needed Resources and Properties have to be added manually

    /** <p>a set of requests/permissions to users of a Work, e.g. a copyright license, 
     *  the public domain, information for distributors</p>
     */
    public static final Resource License = M_MODEL.createResource("https://creativecommons.org/ns#License");

    public static final Property license = M_MODEL.createProperty("https://creativecommons.org/ns#license");
}
